### ISSUE TITLE
No instructions on how to run the project

### ISSUE THREAD

**Issue by rishissahu** [PacktPublishing/The-Ultimate-ChatGPT-Guide-with-React-Native---Develop-Mobile-Apps#3]
Hi there,

I'm trying to run your project, but I'm having trouble because there are no instructions on how to run it. I've cloned the repository, but I don't know what to do next.

Could you please provide some instructions on how to run the project? It would be really helpful if you could include steps to install any dependencies and configure the project properly.

Thank you very much for your time and help.

Best regards,
Rishi

**Comment by Sonakshis** [comment]
Hi 

**In section 1 - 6. Starting The Mobile App Development with Expo Go for ChatGPT Project Development** 
We go through all the steps you need to build the project. 

To open and run a React Native project with Expo on Mac, you can follow these steps:

Ensure that you have Node.js and npm (Node Package Manager) installed on your Mac. You can check their versions by running the following commands in the terminal:

cssCopy code
node --version npm --version

If they are not installed, you can download and install them from the official Node.js website.

Install the Expo CLI globally by running the following command in the terminal:

Copy code
npm install -g expo-cli
Navigate to the directory where your React Native project is located. For example, if your project is in a folder called "my-react-native-app," you can navigate to it using the cd command:

bashCopy code
cd path/to/my-react-native-app
Install the project dependencies by running the following command:

Copy code
npm install
Once the dependencies are installed, you can start the Expo development server by running the following command:

sqlCopy code
expo start
This command will start the Expo development server, and you will see a QR code in the terminal and a Metro Bundler interface in your default web browser.

To view your React Native app on a physical device or emulator, you can use the Expo Client app. Install the Expo Client app from the App Store or Google Play Store on your device.

With the Expo Client app installed, you have a couple of options to open your app:

Scan the QR code displayed in the terminal using your device's camera. This will prompt the Expo Client app to open and load your app.
Open the Expo Client app on your device and sign in with the same account used to start the Expo development server. Once signed in, you should see your project listed, and you can tap on it to open and run your app.
The Expo development server will compile your app and load it in the Expo Client app. You should now see your React Native app running on your device or emulator.

That's it! You have successfully opened and run your React Native project with Expo on Mac. You can make changes to your code, and the changes will be automatically reflected in the running app.

Happy learning!
